# Generated by Django 4.2.1 on 2023-05-31 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='auction/images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=999)),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('PLN', 'PLN')], max_length=3)),
                ('endDate', models.DateTimeField(max_length=999)),
                ('auctioneer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.category')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidPrice', models.DecimalField(decimal_places=2, max_digits=999)),
                ('bidDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Sold', 'Sold'), ('Bid', 'Bid'), ('Cancelled', 'Cancelled')], max_length=200)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.item')),
            ],
        ),
    ]
