# Generated by Django 4.2.1 on 2023-05-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_category_item_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='item',
            name='endDate',
            field=models.DateTimeField(default=None),
        ),
    ]
