# Generated by Django 4.2.1 on 2023-05-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_category_options_alter_item_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='endDate',
            field=models.DateTimeField(),
        ),
    ]
