# Generated by Django 4.2.1 on 2023-06-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_item_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.URLField(default='https://ingoodcompany.asia/images/products_attr_img/matrix/default.png'),
        ),
    ]
