# Generated by Django 4.2.1 on 2023-06-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_item_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='auctioneer',
            new_name='owner',
        ),
    ]
